import Landing from "./Landing";
import Login from "./Login";
import Signup from "./Signup";
import DetailsOne from "./DetailsOne";
import DetailsTwo from "./DetailsTwo";
import Home from "./home/Home";
import Journal from "./home/Journal";
import Test from "./home/Test";
import Chatbot from "./Chatbot";
import Therapist from "./self-care/Therapist";
import SelfCare from "./self-care/SelfCare";
import Meditation from "./self-care/Meditation";
import ChillMusic from "./self-care/ChillMusic";
import YogaTrainer from "./self-care/YogaTrainer";
import Games from "../pages/self-care/Games";
import Forum from "./Forum";
import Insights from "./Insights";
import Profile from "./Profile";
import NotFound from "./NotFound";

export {Landing, Login, Signup, DetailsOne, DetailsTwo, Home, Journal, Test, Chatbot, Therapist, SelfCare, Meditation, ChillMusic, YogaTrainer, Games, Forum, Insights, Profile, NotFound};